"use client";

import { useState, useTransition } from "react";
import { previewBulkFirstAccessInvitesAction, sendBulkFirstAccessInvitesAction } from "./actions";

const labels: Record<string,string> = { missing_email: "Sem e-mail", invalid_email: "E-mail inválido", shared_email: "E-mail compartilhado", invalid_cpf: "CPF inválido", existing_account: "Conflito com conta existente", already_linked: "Já vinculados", inaccessible: "Sem acesso", evaluation_error: "Falha de avaliação", other: "Demais motivos" };
export function BulkFirstAccessInvites({ candidates, title = "Convites de primeiro acesso" }: { candidates: Array<{ id: string; name: string }>; title?: string }) {
  const [selected,setSelected] = useState(() => new Set(candidates.map((item) => item.id))); const [preview,setPreview] = useState<Awaited<ReturnType<typeof previewBulkFirstAccessInvitesAction>> | null>(null); const [report,setReport] = useState<Awaited<ReturnType<typeof sendBulkFirstAccessInvitesAction>>["report"] | null>(null); const [pending,startTransition] = useTransition();
  function calculate() { startTransition(async () => { setReport(null); setPreview(await previewBulkFirstAccessInvitesAction([...selected])); }); }
  function send() { if (!preview?.eligible || !window.confirm(`Enviar/preparar ${preview.eligible} convites?`)) return; startTransition(async () => { const result = await sendBulkFirstAccessInvitesAction(preview.results.filter((item) => item.eligible).map((item) => item.participantId)); setReport(result.report); }); }
  return <section className="max-w-4xl rounded-2xl border border-cyan-500/30 bg-cyan-500/10 p-4"><div className="flex flex-wrap items-start justify-between gap-x-6 gap-y-2"><div><h2 className="font-semibold text-cyan-100">{title}</h2><p className="mt-1 text-sm text-cyan-200">Selecione os cadastros e calcule a elegibilidade pela regra canônica.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => setSelected(new Set(candidates.map((item) => item.id)))} className="inline-flex h-9 shrink-0 items-center whitespace-nowrap rounded-lg border border-slate-600 px-3 text-xs">Selecionar todos os resultados</button><button type="button" onClick={() => setSelected(new Set())} className="inline-flex h-9 shrink-0 items-center whitespace-nowrap rounded-lg border border-slate-600 px-3 text-xs">Limpar</button><button type="button" onClick={calculate} disabled={pending || !selected.size} className="inline-flex h-9 shrink-0 items-center whitespace-nowrap rounded-lg bg-cyan-400 px-3 text-sm font-semibold text-cyan-950 disabled:opacity-50">Calcular elegibilidade ({selected.size})</button></div></div><details className="mt-3"><summary className="cursor-pointer text-sm">Selecionar registros por checkbox</summary><div className="mt-2 grid max-h-48 gap-1 overflow-y-auto sm:grid-cols-2">{candidates.map((item) => <label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={selected.has(item.id)} onChange={(event) => setSelected((current) => { const next=new Set(current); if(event.target.checked) next.add(item.id); else next.delete(item.id); return next; })}/><span className="truncate">{item.name}</span></label>)}</div></details>{preview ? <div className="mt-4 rounded-xl bg-slate-950/60 p-3 text-sm"><p className="font-semibold">{preview.eligible} de {preview.total} cadastros estão aptos a receber convite.</p><div className="mt-2 grid gap-1 sm:grid-cols-2">{Object.entries(preview.reasons).map(([code,count]) => <p key={code}>{labels[code] ?? code}: {count}</p>)}</div><button type="button" onClick={send} disabled={pending || !preview.eligible} className="mt-3 inline-flex h-10 shrink-0 items-center whitespace-nowrap rounded-lg bg-emerald-400 px-4 font-semibold text-emerald-950 disabled:opacity-50">Enviar/preparar {preview.eligible} convites</button></div> : null}{report ? <div className="mt-4 rounded-xl bg-slate-950/60 p-3 text-sm"><p>Preparados: {report.prepared}</p><p>Envio aceito pelo provedor: {report.sent}</p><p>Ignorados: {report.ignored}</p><p>Falharam: {report.failed}</p><details className="mt-2"><summary>Motivos e detalhes</summary>{report.details.map((item) => <p key={item.participantId} className="mt-1 text-xs">{item.status}: {item.reason}</p>)}</details></div> : null}</section>;
}
